# Generated by Django 2.1.2 on 2018-10-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='dias_refeicoes',
            field=models.ManyToManyField(blank=True, null=True, related_name='dias', to='refeitorio.DiasDaSemana', verbose_name='dias das refeições'),
        ),
    ]
